### ISSUE TITLE
Nevergreen server settings not taken into account when it is accessed from other clients 

### ISSUE THREAD

**Issue by cisum-la** [build-canaries/nevergreen#217] opened 2018-04-10 00:06 UTC
Feature Request
Our use case is that we have a URL to a nevergreen server that we have shared with different teams.

The problem is we have setup "Tracking" for multiple GoCD servers on the nevergreen server, but when we access the nevergreen server from our desktop, e.g. http://nevergreen:5000 , the settings need to be reentered for each client/browser (we have multiple people accessing it from their browser). Our expectation is that the settings that were setup on the nevergreen server will be used when accessing it as a client. This also has the advantage that when a new pipeline is added then it can be added to nevergreen server "tracking" option and all the clients would then see the benefit of monitoring that pipeline.

**Comment by GentlemanHal** [comment] 2018-04-10 13:09
Hi @cisum-la, thanks for submitting this feature request.

This is by design, the configuration is stored client side in your browser, the server is completely stateless. This allows a single Nevergreen server to be used by multiple teams and enables us to offer a "build monitor as a service" at https://nevergreen.io

The Backup page allows you to save the current configuration locally or in a GitHub Gist. So currently the best way to set up multiple clients to be the same is to export from one of them, then import into all the others.

This is quite tedious as no auto syncing is performed and we opened issue #191 to think about better options. I'm going to mark this issue as a duplicate, but if you have any good ideas please add them to issue #191

**Comment by SaurabhDeshpande-OpenX** [comment] 2018-04-10 23:43
thanks for above info - i tried to use "Gist" import feature but got attached timeout error.
It is asking for Gist ID, do you know where to enter the Github URL , we have enterprise GitHub and i created my gist in it, but there doesn't seem to be a textbox to specify the Github url.
<img width="809" alt="screen shot 2018-04-09 at 5 10 35 pm" src="https://user-images.githubusercontent.com/36083259/38589163-4f765242-3cde-11e8-8a41-e35fbc90a039.png">

**Comment by GentlemanHal** [comment] 2018-04-11 09:03
Ah, I've never used GitHub Enterprise and didn't realise it required a different URL 😞 

Would you mind opening a separate issue about this with more details of how GitHub Enterprise works? Also I wouldn't have expected a 404 rather than a timeout, so if you were able to add the HTTP response and any server side stack traces to the new issue that would be great.

For now as a workaround I can only suggest either exporting to a regular GitHub account or exporting to a file and emailing / USB that to the other machines, sorry.

**Comment by GentlemanHal** [comment] 2018-09-18 20:05
I'm closing this issue, feel free to open a new one if you still need GitHub Enterprise support!

**Closed by GentlemanHal** 2018-09-18 20:05 UTC
Labels: duplicate
