### ISSUE TITLE
Show info of who broke the build

### ISSUE THREAD

**Issue by boranseref** [build-canaries/nevergreen#128] opened 2016-02-03 11:53 UTC
hi,
we just want to see who broke the build (maybe a git username or ip adress) and which stage is broken.

Can u help us ?

**Comment by GentlemanHal** [comment] 2016-02-03 14:57
Hi @boranseref, thanks for opening this issue.

RE: Who broke the build?

Nevergreen uses the cctray xml format which (for most CI servers) doesn't contain the information of who broke the build. I know [Go](https://www.go.cd/) does include some extra non-standard [message tags](https://github.com/build-canaries/clj-cctray/blob/master/resources/go_example.xml), but since these are non-standard we currently don't use that information. It's also probably very dependant on how you've set up Go as to whether that information is included or useful i.e. if your team pairs on shared machines it's likely you'd end up with a generic shared name.

Integrating with Git is a much bigger piece of work and is unlikely to be done anytime soon, if at all, as we still have lots of improvements that can be made just using the information from the cctray xml. Adding a new integration point brings lots more scope for failures and hard to reproduce bugs.

RE: Showing the stage

If you are using version 0.8.0 or newer then the stage should be clearly shown. This was implemented as part of closing issue #92. If you are using a new enough version could you please provide us with more information about what you do see (a screenshot if possible), as you may have found a bug.

This is also related to issue #66, except that issue also includes showing names for building projects.

**Comment by boranseref** [comment] 2016-02-04 07:51
Thanks for your instant answers. 

We pull nevergreen from dockerhub. Therefore when we run 
"docker run -d -p [host-port]:5000 buildcanariesteam/nevergreen "
command, it runs the version v0.7.0.
How can i get the latest version of nevergreen by dockerhub ?

**Comment by GentlemanHal** [comment] 2016-02-04 13:17
Important caveat! I don't really know how Docker works, perhaps @cowley05 or @manasik might be able to provide more help?

With that in mind my first question would be, have you tried running Docker again?

Because I do know our Docker Image is meant to download the latest release, so if it didn't I suspect you are falling foul of some kind of caching. My assumption is that you ran Docker before we released v0.8.0 so you got the latest at the time, but if you run again now Docker is trying to be clever and just loading the previous cached image or some such.

So I'd investigate that first if I was you.

It's also worth noting v0.8.0 has [breaking changes](https://build-canaries.github.io/2015/10/08/breaking-changes.html), so if you upgrade you'll need to configure your trays again.

You could also consider switching to using [nevergreen.io](https://nevergreen.io), here is some more info about [creating a proxy](https://github.com/build-canaries/nevergreen/wiki/security#adding-a-proxy-for-access-control).

**Comment by GentlemanHal** [comment] 2016-02-05 00:33
`--no-cache=true` from https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#build-cache

**Comment by GentlemanHal** [comment] 2016-03-24 00:33
I'm going to combine this issue with #66 and close this one.

@boranseref If you are still having problems with Docker please raise an issue at https://github.com/build-canaries/nevergreen-docker/issues

**Closed by GentlemanHal** 2016-03-24 00:33 UTC
Labels: new feature
