### ISSUE TITLE
React error - Maximum update depth exceeded

### ISSUE THREAD

**Issue by Eric-Bourry** [build-canaries/nevergreen#234] opened 2018-06-07 08:29 UTC
I'm using the latest standalone release, and when I let the monitor run for a while, I eventually get a react error (https://reactjs.org/docs/error-decoder.html?invariant=185) that completely freezes the monitor.

Hopefully, a new release can be published with a fix to this issue, that completely prevents the tool from being used.

**Comment by GentlemanHal** [comment] 2018-06-09 14:51
Hi @Eric-Bourry, thanks for submitting this bug report.

This is not an error I've seen before and we have been running the latest release at work for months. So I'm going to need some more help to get to the bottom of this! 

1. Can you confirm you are running `v1.0.0+695.31a2522 Lapis Lazuli` locally via the downloaded jar?
2. Which browser are you running in? e.g. `Chrome 54.0.2840.71 (64-bit)`
3. Which CI server are you monitoring? e.g. `Jenkins` or `GoCD` etc
4. How long does it take for the error to be thrown? e.g. Hours, days, months

Are you able to provide anonymised configuration? Unfortunately you'll have to do this yourself by backing up locally and replacing any hostnames or project names you aren't happy to share.

Also it would be helpful if you could try either of the following:

- Remove any other trays and just monitor `https://builds.apache.org/cc.xml` to see if the error is still thrown.

This is the Apaches public Jenkins instance which I use to do most testing. This would just help remove some variables from the equation.

- Download and run a development build from source code.

We've made quite a few changes since the last release so we may have fixed this as side effect of other changes. If not, at least we'd get the full stack trace which will point to the exact component throwing the error.

Thanks!

**Comment by Eric-Bourry** [comment] 2018-06-17 18:12
Hi @GentlemanHal, thanks for your prompt reply, I will provide you with the information shortly. Out of curiosity, is there a plan to release a new version soon, so that I can test if the issue is fixed as a side effect?

**Comment by Eric-Bourry** [comment] 2018-06-18 07:27
Here are the answers to your questions:

1. I'm running the following version, from the Jar of the latest release: v1.0.0+588.d7c07c1 Lapis Lazuli
2. I'm running inside CefSharp.WinForms.ChromiumWebBrowser (v 63.0.3)
3. I'm monitoring a CC.Net server (builds are run through msbuild)
4. It usually takes a few minutes, sometimes seconds. My current workaround is to manually refresh the page every 2 minutes, but that's not very convenient

Thanks

**Comment by GentlemanHal** [comment] 2018-06-20 13:28
Wow, I wasn't expecting a few minutes! 😱 

Given the details you've provided, the most likely cause is the browser you are using. I wasn't even sure what that was and had to look it up. If I understand correctly it allows you to embed a browser in a .NET application?

To narrow this down could you try:

1. Monitoring your CC.Net server via an up-to-date standalone Chrome install
2. Monitoring `https://builds.apache.org/cc.xml` via CefSharp.WinForms.ChromiumWebBrowser

**Comment by Eric-Bourry** [comment] 2018-08-02 12:32
Thanks a lot, I will download this build and try it

2018-07-23 15:28 GMT+02:00 Christopher Martin <notifications@github.com>:

**Comment by GentlemanHal** [comment] 2018-11-10 15:18
Hey @Eric-Bourry, I'm going to close this issue for now as I'm unable to reproduce and no one else has reported a similar issue. My best guess is it is something to do with the browser you are using.

If you have anymore information, please leave a comment and I'll re-open if necessary.

**Closed by GentlemanHal** 2018-11-10 15:18 UTC
Labels: bug, help wanted
